//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Product.Service.OrderProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OrderProxy.IOrderContract", SessionMode=System.ServiceModel.SessionMode.Required)]
    public interface IOrderContract {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderContract/Get", ReplyAction="http://tempuri.org/IOrderContract/GetResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Order.Domain.OrderInfo))]
        Order.Domain.OrderInfo Get(object id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderContract/Save", ReplyAction="http://tempuri.org/IOrderContract/SaveResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Order.Domain.OrderInfo))]
        object Save(Order.Domain.OrderInfo entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IOrderContract/Update", ReplyAction="http://tempuri.org/IOrderContract/UpdateResponse")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        void Update(Order.Domain.OrderInfo entity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IOrderContractChannel : Product.Service.OrderProxy.IOrderContract, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderContractClient : System.ServiceModel.ClientBase<Product.Service.OrderProxy.IOrderContract>, Product.Service.OrderProxy.IOrderContract {
        
        public OrderContractClient() {
        }
        
        public OrderContractClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderContractClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Order.Domain.OrderInfo Get(object id) {
            return base.Channel.Get(id);
        }
        
        public object Save(Order.Domain.OrderInfo entity) {
            return base.Channel.Save(entity);
        }
        
        public void Update(Order.Domain.OrderInfo entity) {
            base.Channel.Update(entity);
        }
    }
}
